services:
  postgres:
    image: postgres:17.9-alpine3.23
    container_name: bizcord_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bizcord
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d bizcord" ]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    image: bizcord-backend:latest
    container_name: bizcord_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      APP_CORS_ALLOWED_ORIGIN_PATTERNS: "http://host.docker.internal:80,http://host.docker.internal:8080"
      DB_URL: jdbc:postgresql://postgres:5432/bizcord
      DB_USERNAME: admin
      DB_PASSWORD: admin
    volumes:
      - ./uploads:/app/uploads
    expose:
      - "8080"

  frontend:
    image: bizcord-frontend:latest
    container_name: bizcord_frontend
    environment:
      BACKEND_URL: http://host.docker.internal:8080
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"